[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "0x282C34"
bright_foreground = "0xe6efff"
foreground = "0xbac1ca"

[font]
size = 12

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Shift|Alt"

[window]
opacity = 0.8
