#!/usr/bin/env /bin/bash
# Check files

options=(
'--border-color=#005577'
'--selection-color=#47b413'
'--prompt-text=copy:'
)

menu="tofi ${options[@]}"

folder="$HOME/Documents/Pessoal"
[ -d $folder ] || mkdir $folder
[ -f $folder/bookmarks ] || touch $folder/bookmarks

wl-copy "$(cat $folder/bookmarks | grep -v "^#" | grep -v "^$" | $menu | cut -f 1 -d " ")"
