#!/usr/bin/bash
source "/etc/os-release"
case "$ID" in
    "alpaquita") logo="";;
    "alpine") logo="";;
    "amazon") logo="";;
    "android") logo="";;
    "arch") logo="";;
    "artix") logo="";;
    "centOS") logo="";;
    "debian") logo="";;
    "dragonFly") logo="";;
    "emscripten") logo="";;
    "endeavourOS") logo="";;
    "fedora") logo="";;
    "freeBSD") logo="";;
    "garuda") logo="﯑";;
    "gentoo") logo="";;
    "hardenedBSD") logo="ﲊ";;
    "illumos") logo="";;
    "linux") logo="";;
    "mabox") logo="";;
    "macos") logo="";;
    "manjaro") logo="";;
    "mariner") logo="";;
    "midnightBSD") logo="";;
    "mint") logo="";;
    "netBSD") logo="";;
    "nixOS") logo="";;
    "openBSD") logo="";;
    "openSUSE") logo="";;
    "oracleLinux") logo="";;
    "pop") logo="";;
    "raspbian") logo="";;
    "redhat") logo="";;
    "redHatEnterprise") logo="";;
    "redox") logo="";;
    "solus") logo="ﴱ";;
    "suse") logo="";;
    "ubuntu") logo="";;
    "unknown") logo="?";;
    "windows") logo="";;
    *) exit 1;;
esac &&
    printf "%s" $logo
