#!/usr/bin/bash
source "/etc/os-release"
case "$ID" in
    "arch") logo="";;
    "alpaquita") = "";;
    "alpine") = "";;
    "amazon") = "";;
    "android") = "";;
    "arch") = "";;
    "artix") = "";;
    "centOS") = "";;
    "debian") = "";;
    "dragonFly") = "";;
    "emscripten") = "";;
    "endeavourOS") = "";;
    "fedora") = "";;
    "freeBSD") = "";;
    "garuda") = "﯑";;
    "gentoo") = "";;
    "hardenedBSD") = "ﲊ";;
    "illumos") = "";;
    "linux") = "";;
    "mabox") = "";;
    "macos") = "";;
    "manjaro") = "";;
    "mariner") = "";;
    "midnightBSD") = "";;
    "mint") = "";;
    "netBSD") = "";;
    "nixOS") = "";;
    "openBSD") = "";;
    "openSUSE") = "";;
    "oracleLinux") = "";;
    "pop") = "";;
    "raspbian") = "";;
    "redhat") = "";;
    "redHatEnterprise") = "";;
    "redox") = "";;
    "solus") = "ﴱ";;
    "sUSE") = "";;
    "ubuntu") = "";;
    "unknown") = "?";;
    "windows") = "";;
    *) exit 1;;
esac &&
case "$1" in
    "name") printf "%s\n" "$NAME" ;;
    "logo") printf "%s\n" "$logo" ;;
    *) printf "%s %s\n" "$logo" "$NAME" ;;
esac
