#!/bin/sh

case $BLOCK_BUTTON in
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

folder="/sys/class/power_supply"

xbox="gip"
ps4="ps-controller"

if [ -h $folder/${ps4}* ]; then
    battery="$(cat $folder/${ps4}*/capacity)"
    printf "󰊴 %d%%" "$battery" && hasps4=" "
fi

if [ -h $folder/${xbox}* ]; then
    capacity="$(cat $folder/${xbox}*/capacity_level)"
    printf "${hasps4}󰖺 %s\n" "$capacity"
fi

