#!/bin/sh

if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
    percentage=$(awk '/^\s*w/ { print int($3 * 100 / 70) }' /proc/net/wireless)
    case 1 in
        $((percentage >= 85)) ) icon="󰤨";;
        $((percentage >= 60)) ) icon="󰤥";;
        $((percentage >= 40)) ) icon="󰤢";;
        $((percentage >= 20)) ) icon="󰤟";;
        $((percentage >= 1)) ) icon="󰤯";;
    esac
    wifiicon="$icon ${percentage}%"
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="󰤮 " || wifiicon="󰤫 "
fi

printf "%s%s%s\n" "$wifiicon" "$(sed "s/down/󰈂 down/;s/up//" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/🔒/" /sys/class/net/tun*/operstate 2>/dev/null)"
