#!/usr/bin/env /bin/sh
# Check files
tofi="$HOME/.config/hypr/scripts/tofi/tofi.sh"


folder="$HOME/Documents/Pessoal"
[ -d $folder ] || mkdir $folder
[ -f $folder/bookmarks ] || touch $folder/bookmarks
wl-copy "$(cat $folder/bookmarks | grep -v "^#" | grep -v "^$" | $tofi --prompt-text \"\" | cut -f 1 -d " ")"
