#!/usr/bin/bash
# This script generates a local config for the current machine in case
# it still doesn't exist

read -r -a monitors <<< "$(hyprctl monitors | awk '/^Monitor/ {printf $2 " "}')"
read -r -a modes <<< "$(hyprctl monitors | awk '$1 ~ /availableModes/ {printf $2 " "}')"

cat << EOF
# Autogenerated Local Hyprland config
# Change it to the needs of your local machine
# Or delete this no generate a new one!

EOF

for ((i = 0; i < ${#monitors[@]}; i++)); do
    echo '$monitor'$i=${monitors[$i]}
done

offset=0
for ((i = 0; i < ${#monitors[@]}; i++)); do
    echo 'monitor=$monitor'$i,${modes[$i]},${offset}x0,1
    offset=$((offset+1920));
done

cat << EOF
\$mainMod = SUPER
# You can change the cursor size
env = XCURSOR_SIZE,24

EOF

# If the user is using nvidia
if lspci -vnnn | perl -lne 'print if /^\d+\:.+(\[\S+\:\S+\])/' | grep VGA &> /dev/null; then
cat << EOF

# Nvidia env variables
env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto

EOF
fi

cat << EOF
# Configure mouse/keyboard
input {
    kb_layout = pt
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = false
        natural_scroll = false
        tap-to-click = true
        tap-and-drag = false
    }

    accel_profile = flat
    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.
}

# Configure workspaces for each monitor
# Monitor 1
workspace=1, monitor:\$monitor0, default:true
workspace=2, monitor:\$monitor0, default:true
workspace=3, monitor:\$monitor0, default:true
workspace=4, monitor:\$monitor0, default:true
workspace=5, monitor:\$monitor0, default:true
workspace=6, monitor:\$monitor0, default:true
workspace=7, monitor:\$monitor0, default:true
workspace=8, monitor:\$monitor0, default:true
workspace=9, monitor:\$monitor0, default:true
workspace=10, monitor:\$monitor0, default:true

# Switch workspaces with mainMod + [0-9]
bind = \$mainMod, 1, workspace, 1
bind = \$mainMod, 2, workspace, 2
bind = \$mainMod, 3, workspace, 3
bind = \$mainMod, 4, workspace, 4
bind = \$mainMod, 5, workspace, 5
bind = \$mainMod, 6, workspace, 6
bind = \$mainMod, 7, workspace, 7
bind = \$mainMod, 8, workspace, 8
bind = \$mainMod, 9, workspace, 9
bind = \$mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = \$mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = \$mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = \$mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = \$mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = \$mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = \$mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = \$mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = \$mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = \$mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = \$mainMod SHIFT, 0, movetoworkspacesilent, 10

EOF

wn=11
fk=1

# Workspaces for extra monitors
for ((m = 1; m < ${#monitors[@]}; m++)); do
    wni=wn;
    fki=fk
    for ((i = 0; i < 4; i++)); do
        echo "workspace=$((wni++)), monitor:\$monitor$((m)), default:true"
    done
    wni=wn;
    fki=fk
    for ((i = 0; i < 4; i++)); do
        echo "bind = \$mainMod, F$((fki++)), workspace, $((wni++))"
    done
    wni=wn;
    fki=fk
    for ((i = 0; i < 4; i++)); do
        echo "bind = \$mainMod SHIFT, F$((fki++)), movetoworkspacesilent, $((wni++))"
    done
    wn=wni
    fk=fki
done

