# Text editors
neovim
vim
# Others
unrar
fzf
tmux
mandoc
ruby
dash
arch-install-scripts
stow
polkit
dosfstools
yt-dlp
zsh
exa
rsync
alsa-utils
tor
inetutils
neofetch
zathura
zathura-pdf-mupdf
newsboat
openssh
bat
lf-sixel-git
cronie
go
nodejs
mpc
mpd
libnotify
sshfs
fuse3
playerctl
calcurse
npm
ntfs-3g
ncmpcpp
base-devel
networkmanager
wget
curl
lynx
notmuch
starship
dunst
ruby
nim
nimble
webkit2gtk
abook
htop-vim
urlview
cronwhip
