# Wayland
swayidle
swaylock
wlroots
hyprland
sway
gammastep
wofi
foot
waybar
qt5-wayland
qt5ct
webkit2gtk
swww
grim
slurp
imv
pavucontrol
ffmpegtumbnailer
# Gtk stuff
gtk-engine-murrine
gnome-themes-extra
