# ArchLinux - Xorg package list
# Wayland
swayidle
swaylock
wlroots-git
hyprland
wofi
foot
waybar-hyprland-git
qt5-wayland
qt5ct
webkit2gtk
swww
grim
slurp
pavucontrol
ffmpegtumbnailer
# Gtk stuff
gtk-engine-murrine
gnome-themes-extra
