#!/usr/bin/zsh
# Plugins are stored to $HOME/.local/share/zsh

declare -A plugin_repos

# Plugins are stored to $HOME/.local/share/zsh
ZSH_PLUGIN_DIR="$HOME/.local/share/zsh"

if [ ! -d "$ZSH_PLUGIN_DIR" ]; then
    mkdir -p "$ZSH_PLUGIN_DIR"
    plugin-sync
fi

plugin-load() {
    local cdir="$PWD"
    cd $ZSH_PLUGIN_DIR
    for plugin in *; do
        local pdir="$ZSH_PLUGIN_DIR/$plugin"
        [ -d "$pdir" ] && source $pdir/*.plugin.zsh
    done
    if [ -r "$cdir" ]; then
        cd $cdir
    else
        cd $cdir
    fi
}

plugin-sync() {
    local cdir="$PWD"
    cd $ZSH_PLUGIN_DIR
    for plugin in "${plugins[@]}"; do
        local pname="${plugin//*\/}"
        local prepo="https://github.com/$plugin"
        local pdir="$ZSH_PLUGIN_DIR/$pname"
        if [ ! -d "$pdir" ]; then
            echo "Plugin $pname is not installed, cloning $prepo..."
            git clone "$prepo"
        else
            cd "$pdir"
            echo "Updating $pname..."
            git pull
            cd ..
        fi
    done
    echo "Loading plugins..."
    plugin-load
    if [ -r "$cdir" ]; then
        cd $cdir
    else
        cd
    fi
}
