#!/usr/bin/zsh

# Load version control information
autoload -Uz vcs_info

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git:*' formats 'on %b'

## PROMPT CONFIG
lcrv() {
    rv=$?
    if [ $rv -gt 0 ]; then
        echo "%F{red}> %f"
    else
    echo "%F{blue}> %f"
    fi
}

setopt prompt_subst

PROMPT='%F{magenta}%~%f
$(lcrv)'

RPROMPT=\$vcs_info_msg_0_

# Add a newline before the prompt
precmd() { vcs_info; precmd(){ vcs_info; echo "" }}
alias clear='clear; precmd() { vcs_info; precmd(){ vcs_info; echo "" }}'
