#!/usr/bin/zsh
## PROMPT CONFIG

# Load version control information
autoload -Uz vcs_info
# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '%b %m'

# Last command return value
lcrv() {
    rv=$?
    if [ $rv -gt 0 ]; then
        echo "%F{red}$rv%f "
    fi
}

if [[ "$(tty)" == "/dev/tty"* ]]; then
    PROMPT='%B%F{green}%n%f%F{yellow}@%f%F{red}%m %B%f%F{magenta}%~%b %F{green}${vcs_info_msg_0_}
%B%F{red}$(lcrv)%f%F{blue}%b$%f '
else
    PROMPT='%B%F{magenta}%~ %b%F{green}${vcs_info_msg_0_}
%B%F{red}$(lcrv)%f%F{blue}#%b%f '
    RPROMPT="%F{black}%n%f%F{black}@%f%F{black}%m%f"
fi

# Add a newline before the prompt
precmd() { vcs_info; precmd(){ vcs_info; echo "" }}
alias clear='clear; precmd() { vcs_info; precmd(){ vcs_info; echo "" }}'
