#!/usr/bin/sh
tofi="$HOME/.config/hypr/scripts/tofi/tofi.sh"
file="$HOME/.config/hypr/scripts/emoji_picker/emojis"
emoji="$($tofi --prompt-text \"\" < $file | cut -d " " -f 1)"
printf "${emoji%%"\n"}" | wl-copy
