#!/usr/bin/env /bin/bash
# Check files
if [ -z "$BOOKMARKS_FILE" ]; then
    exit 1
fi

bookmark="$(cat $BOOKMARKS_FILE | grep -v "^#" | grep -v "^$" | dmenu -c -b -bw 1 -l 20 -p "Select Bookmark:" | cut -f 1 -d " ")"
printf ${bookmark%%"\n"} | xclip -sel clip
