#!/usr/bin/bash

config_file="$HOME/.dalis/config"
source "$config_file"

case "${#monitors[@]}" in
    1)
        xrandr --output ${monitors[0]} --primary --mode 1920x1080 --rate ${refresh[0]}
        ;;
    2)
        echo xrandr --output ${monitors[1]} --primary --mode 1920x1080 --rate ${refresh[1]}\
        --output ${monitors[0]} --mode 1920x1080 --rate ${refresh[0]} --left-of ${monitors[1]}
        ;;
    3)
        xrandr --output ${monitors[1]} --primary --mode 1920x1080 --rate ${refresh[1]}\
        --output ${monitors[0]} --mode 1920x1080 --rate ${refresh[0]} --left-of ${monitors[1]}\
        --output ${monitors[2]} --mode 1920x1080 --rate ${refresh[2]} --right-of ${monitors[1]}
        ;;
esac
