preload = /home/dario/.config/wallpaper/wallpaper.png
#if more than one preload is desired then continue to preload other backgrounds
# .. more preloads

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = HDMI-A-1,contain:/home/dario/.config/wallpaper/wallpaper.png
wallpaper = DP-1,contain:/home/dario/.config/wallpaper/wallpaper.png
wallpaper = HDMI-A-2,contain:/home/dario/.config/wallpaper/wallpaper.png
#if more than one monitor in use, can load a 2nd image
splash = false
