#!/usr/bin/bash
# Here the system will be configured

## Dalis repo location ##

## DISPLAY ##

# Monitor Setup
# Monitor1 is the primary monitor

#monitor1="DP-0"
#monitor2="HDMI-0"
#monitor3="HDMI-1"

# Persistent refresh rates

#rr1="144.00"
#rr2="60.00"
#rr3="60.00"

# From left to right
# Up to 3 monitors in the array

#monitors=( "$monitor3" "$monitor1" "$monitor2" )
#refresh=( "60.00" "144.00" "60.00" )

## BACKUPS ##

#backup_dirs=(
#"$HOME/Documents"
#"$HOME/Media"
#"$HOME/.wine/drive_c/users/dario"
#)

#backup_disks=( "/mnt/Barracuda" "/mnt/Robalo" )
#temp_backup_dirs=( "$HOME/Documents" "$HOME/.wine/drive_c/users/dario" )
#temp_backup_keep=( 10 10 )

## Keyboard ##

#keyboard_layout="pt"

#keyboard_map="$HOME/Documents/Pessoal/keymaps/default"

## Variables used by scripts ##

#keymaps_folder="$HOME/Documents/Pessoal/keymaps"
#consoom_folder="$HOME/Documents/Pessoal/consoom"
#streaks_folder="$HOME/Documents/Pessoal/streaks"
