add_newline = false

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
ssh_symbol = " "
format = 'in [$hostname](bold purple) '
trim_at = "."
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[󰧂](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[󰧂](bold red)"
vicmd_symbol = "[󰧀](green)"

# configure directory
[directory]
read_only = "  "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
format = 'in [ $path](bold blue) '
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"


[battery]
full_symbol = '󰂏 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 20%
threshold = 20
style = 'bold red'

[[battery.display]] # 'bold yellow' style when capacity is between 10% and 40%
threshold = 40
style = 'bold yellow'

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[nodejs]
format = "via [ Node.js](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = "󰲒 "

[haxe]
symbol = "⌘ "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[os]
format = "on [($name $symbol)]($style)"
style = "bold blue"
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = "? "
Windows = " "

[package]
symbol = " "

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

# ~/.config/starship.toml
# ~/.config/starship.toml
