#!/usr/bin/bash
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus

dconfig="$HOME/Documents/Dalis/.config"
dhome="$HOME/Documents/Dalis/home"
config=()
home=()
devices=(
	#Dispositivos definidos em ssh
	"dariolaptop"
)
icon="/home/dario/.local/share/icons/dalis/thumbsup.png"
for i in $(ls $dconfig); do
	config+=("$HOME/.config/$i")
done
for i in $(ls -A $dhome); do
	home+=("$HOME/$i")
done

for device in ${devices[@]}; do
	# Verificar conexão
	ssh -q -o BatchMode=yes  -o StrictHostKeyChecking=no -o ConnectTimeout=5 "$device" 'exit 0'
	go="$?"
	if [ "$go" = "0" ]; then
	    #Sincronizar configuração
	    rsync -uvrP --delete ${config[@]} $device:~/.config
	    rsync -uvrP --delete ${home[@]} $device:
        #mpv --no-video "$HOME/.scripts/media/notification.wav"
        notify-send -i $icon "Laptop sync 💻" "Devices ${devices[@]} updated with success!"
	fi
done
