#!/usr/bin/bash
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus

devices=(
	#Dispositivos definidos em ssh
	"dariolaptop"
)

dotfilesf="$HOME/.dotfiles"

for device in ${devices[@]}; do
	# Verificar conexão
	ssh -q -o BatchMode=yes  -o StrictHostKeyChecking=no -o ConnectTimeout=5 "$device" 'exit 0'
	go="$?"
	if [ "$go" = "0" ]; then
	    #Sincronizar configuração
	    rsync -uvrP --delete --delete "$dotfilesf"/* "$device:$dotfilesf"
        #mpv --no-video "$HOME/.scripts/media/notification.wav"
	fi
done && notify-send -i $icon "Laptop sync" "Devices ${devices[@]} updated with success!" ||
notify-send -u critical "Laptop sync" "There were problems syncing devices ${devices[@]}. Check the logs!"
