#!/usr/bin/bash
#Extra stuff you have to do to make hyprland work with nvidia, all automated

sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/{ s/\"^/nvidia_drm.modeset=1\" }' "/etc/default/grub"

grub-mkconfig -o /boot/grub/grub.cfg

printf "MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)\n" >> /etc/mkinitcpio.conf

mkinitcpio --config /etc/mkinitcpio.conf --generate /boot/initramfs-custom.img

printf "options nvidia-drm modeset=1\n" >> /etc/modprobe.d/nvidia.conf
