# Desktop Config

#$monitor1=HDMI-A-2
$monitor1=DP-1
$monitor2=HDMI-A-1

monitor=$monitor1,1920x1080@165,1920x0,1
monitor=$monitor2,1920x1080@60,0x0,1

#monitor=$monitor2,1920x1080@60,1920x0,1

$mainMod = SUPER

# Enable swayidle for desktop

# Caga nessa merda ai
# exec-once = ~/.config/swaylock/init_desktop.sh

# Variables
env = XCURSOR_SIZE,24
env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

input {
    kb_layout = pt
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = false
        natural_scroll = false
        tap-to-click = true
        tap-and-drag = false
    }

    accel_profile = flat
    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.
}

# workspaces
workspace=1, monitor:$monitor1, default:true
workspace=2, monitor:$monitor1, default:true
workspace=3, monitor:$monitor1, default:true
workspace=4, monitor:$monitor1, default:true
workspace=5, monitor:$monitor1, default:true
workspace=6, monitor:$monitor1, default:true
workspace=7, monitor:$monitor1, default:true
workspace=8, monitor:$monitor1, default:true
workspace=9, monitor:$monitor1, default:true
workspace=10, monitor:$monitor1, default:true

workspace=11, monitor:$monitor2, default:true
workspace=12, monitor:$monitor2, default:true
workspace=13, monitor:$monitor2, default:true
workspace=14, monitor:$monitor2, default:true

workspace=15, monitor:$monitor2, default:true
workspace=16, monitor:$monitor2, default:true
workspace=17, monitor:$monitor2, default:true
workspace=18, monitor:$monitor2, default:true

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod, F1, workspace, 11
bind = $mainMod, F2, workspace, 12
bind = $mainMod, F3, workspace, 13
bind = $mainMod, F4, workspace, 14

bind = $mainMod, F5, workspace, 15
bind = $mainMod, F6, workspace, 16
bind = $mainMod, F7, workspace, 17
bind = $mainMod, F8, workspace, 18

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, movetoworkspacesilent, 5
bind = $mainMod SHIFT, 6, movetoworkspacesilent, 6
bind = $mainMod SHIFT, 7, movetoworkspacesilent, 7
bind = $mainMod SHIFT, 8, movetoworkspacesilent, 8
bind = $mainMod SHIFT, 9, movetoworkspacesilent, 9
bind = $mainMod SHIFT, 0, movetoworkspacesilent, 10

bind = $mainMod SHIFT, F1, movetoworkspacesilent, 11
bind = $mainMod SHIFT, F2, movetoworkspacesilent, 12
bind = $mainMod SHIFT, F3, movetoworkspacesilent, 13
bind = $mainMod SHIFT, F4, movetoworkspacesilent, 14

bind = $mainMod SHIFT, F5, movetoworkspacesilent, 15
bind = $mainMod SHIFT, F6, movetoworkspacesilent, 16
bind = $mainMod SHIFT, F7, movetoworkspacesilent, 17
bind = $mainMod SHIFT, F8, movetoworkspacesilent, 18
