COLORSCHEME everforest

    foot-config:

        background: #272e33
        foreground: #d3c6aa
        regular0: #4a4b50
        regular1: #e67e80
        regular2: #a7c080
        regular3: #dbbc7f
        regular4: #7fbbb3
        regular5: #d699b6
        regular6: #83c092
        regular7: #d3c6aa
        bright0: #475258
        bright1: #e67e80
        bright2: #a7c080
        bright3: #dbbc7f
        bright4: #7fbbb3
        bright5: #d6999b
        bright6: #83c092
        bright7: #d3c6aa

    hyprland-config:

        active_border: rgb(ea6962) rgb(e3a84e) 54deg
        inactive_border: rgb(595959)

    dunst-config:

        background: #1d2021
        foreground: #ebdbb2
        frame_color: #ebdbb2
        highlight: #ebdbb2

    waybar-config:

        low: #1d2021
        medium: #32302f
        high: #ebdbb2

END

COLORSCHEME gruvbox

    foot-config:

        background: #1d2021
        foreground: #ebdbb2
        regular0: #665c54
        regular1: #ea6962
        regular2: #a9b665
        regular3: #d8a657
        regular4: #7daea3
        regular5: #d3869b
        regular6: #89b482
        regular7: #dfbf8e
        bright0: #928c74
        bright1: #ea6962
        bright2: #a9b665
        bright3: #d8a657
        bright4: #7daea3
        bright5: #a3869b
        bright6: #89b482
        bright7: #dfbf8e

    hyprland-config:

        col.active_border: rgb(ea6962) rgb(e3a84e) 54deg
        col.inactive_border: rgb(595959)

    dunst-config:

        background: #1d2021
        foreground: #ebdbb2
        frame_color: #ebdbb2
        highlight: #ebdbb2

    waybar-config:

        low: #1d2021
        medium: #32302f
        high: #ebdbb2

END

COLORSCHEME kanagawa
    foot-config:
    hyprland-config:
    dunst-config:
    waybar-config:
END

COLORSCHEME rose-pine
    foot-config:
    hyprland-config:
    dunst-config:
    waybar-config:
END

COLORSCHEME onedark
    foot-config:
    hyprland-config:
    dunst-config:
    waybar-config:
END
