COLORSCHEME rose-pine

   foot-config:

        foreground: #e0def4
        background: #191724
        regular0: #1f1d2e
        bright0: #26233a
        regular1: #eb6f92
        bright1: #eb6f92
        regular2: #f6c177
        bright2: #f6c177
        regular3: #ebbcba
        bright3: #ebbcba
        regular4: #31748f
        bright4: #31748f
        regular5: #c4a7e7
        bright5: #c4a7e7
        regular6: #9ccfd8
        bright6: #9ccfd8
        regular7: #6e6a86
        bright7: #908caa

    hyprland-config:

        active_border: rgb(d19166)
        inactive_border: rgb(595959)

    dunst-config:

        background: #1f1f28
        foreground: #dcd7ba
        frame_color: #dcd7ba
        highlight: #dcd7ba

    waybar-config:

        low: #1f1f28
        medium: #32302f
        high: #dcd7ba

END
