#!/usr/bin/sh

options=(
'--config'
'~/.config/sway/scripts/tofi/fullscreen.conf'
)

editor="tofi ${options[@]}"
#editor="tofi --border-color=#005577 --selection-color=#47b413"

file="$HOME/.config/sway/scripts/emoji_picker/emojis"
emoji="$(cat $file | $editor | cut -d " " -f 1)"
printf "${emoji%%"\n"}" | wl-copy
