#!/bin/bash

barsize=20

# 1º argument -> battery percentage
# 2º argument -> size of the bar
printbar(){
    dots=$(($2 / (100 / $1)))
    spaces=$(($2 - $dots))
    printf "["
    # for ((i = 1; i <= $2; i++)); do
    #     if [ $i -le $spaces ]; then
    #         printf "*"
    #     else
    #         printf " "
    #     fi
    # done
    for ((i = 0; i < $dots; i++)); do
        printf "*"
    done
    for ((i = 0; i < $spaces; i++)); do
        printf " "
    done
    printf "]"
}

# for battery in /sys/class/power_supply/BAT?*; do
#     cap=$(cat $battery/capacity)
#     printf "$(printbar $cap $barsize) $(cat $battery/state)"
# done
# 
# if empty; then
#     echo No Battery
# fi

echo $(printbar 10 20)
