#!/bin/bash

barsize=20

# 1º argument -> battery percentage
# 2º argument -> size of the bar
printbar(){
    dots=$(($2 * $1 / 100))
    spaces=$(($2 - $dots))
    batstr="["
    for ((i = 0; i < $dots; i++)); do
        batstr="${batstr}*"
    done
    for ((i = 0; i < $spaces; i++)); do
        batstr="${batstr} "
    done
    batstr="${batstr}]"
    echo $batstr
}

if [ -L /sys/class/power_supply/BAT* ]; then
    for battery in /sys/class/power_supply/BAT?*; do
        cap=$(cat $battery/capacity)
        echo "$(printbar $cap $barsize) ${cap}% $(cat $battery/status)"
    done
else
    echo No Battery
fi
