#!/bin/bash

# Prints the current volume or 🔇 if muted.
vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print 🔇 and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo 🔇 muted && exit

vol="${vol#Volume: }"

split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

if [ $vol -gt 100 ]; then
    echo "🔴 $vol%"
elif [ $vol -gt 60 ]; then
    echo " $vol%"
elif [ $vol -gt 20 ]; then
    echo " $vol%"
else
    echo " $vol%"
fi
