#!/usr/bin/bash
old_ifs="$IFS"
IFS=":"
font="JetBrainsMono:size=15"
options="Exit dwm:Load Xresources:Restart dwm:Lock:Reboot:Poweroff"
#case $(for option in ${options[@]}; do printf "$option\n";done | dmenu -c -bw 2 -fn "$font" -l 5) in
case $(for option in ${options[@]}; do printf "$option\n";done | dmenu -l 6 -p "Select option:") in
	*"Exit dwm") killall startdwm || killall dwm;;
	*"Poweroff") poweroff;;
	*"Xresources") [[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources;;
	*"Reboot") reboot;;
	*"Restart dwm") killall dwm;;
	*"Lock") slock;;
esac
