#!/bin/env /bin/python3
from sys import argv
from time import sleep
file_path = "/home/dario/.scripts/statusbar/dwmblocks/music-state"
def loop(maxim, sep, stin, path):
    string = str(stin) + str(sep) 
    while True:
        file = open(path, "w")
        file.write(string[0:int(maxim)]+ "\n")
        file.close()
        string = string.replace(string[0], "", 1) + string[0]
        sleep(1)
loop(argv[1], argv[2], argv[3], file_path)
